[env]
# EMCC_CFLAGS = "-s ASYNCIFY -s USE_GLFW=3 -DPLATFORM_WEB -DGRAPHICS_API_OPENGL_ES2 -sEXPORTED_FUNCTIONS=_main,_on_resize -sEXPORTED_RUNTIME_METHODS=ccall,cwrap"
EMCC_CFLAGS = "-O2 -sUSE_GLFW=3 -sASSERTIONS=1 -sWASM=1 -sASYNCIFY -sGL_ENABLE_GET_PROC_ADDRESS=1"
